// TODO: Remove me... fast
export const Auth0JWT = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJGWW5uSFdwSk1jemVNYkJwbWllaUhXTmQySVBhcXFTYyIsInNjb3BlcyI6eyJ1c2VycyI6eyJhY3Rpb25zIjpbInJlYWQiLCJ1cGRhdGUiLCJjcmVhdGUiXX19LCJpYXQiOjE0NzkwMTA0NTMsImp0aSI6ImQ1NWI1OWI2NzljZDcwOGY4YzJiNGUzYjRkNzA4ODYzIn0.mFCO9dg1_UHptLuEr2b8BJsoVGPxm_jvl3Jmwp1TgxY'
export const Auth0ApiUrl = 'https://spac.auth0.com/api/v2'
export const FusionApiUrl = 'https://w9fyq1dyrl.execute-api.us-west-2.amazonaws.com/FusionApiProd'

// Posts
export const LOAD_POSTS_REQUEST = 'LOAD_POSTS_REQUEST'
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS'
export const LOAD_POSTS_FAILURE = 'LOAD_POSTS_FAILURE'

// Single Post
export const LOAD_POST_REQUEST = 'LOAD_POST_REQUEST'
export const LOAD_POST_SUCCESS = 'LOAD_POST_SUCCESS'
export const LOAD_POST_FAILURE = 'LOAD_POST_FAILURE'

// Users List
export const GET_USERS_REQUEST = 'GET_USERS_REQUEST'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE'

// Users Details
export const GET_USER_BY_ID_REQUEST = 'GET_USER_BY_ID_REQUEST'
export const GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS'
export const GET_USER_BY_ID_FAILURE = 'GET_USER_BY_ID_FAILURE'

export const GET_USER_REMAINING_WORKOUTS_REQUEST = 'GET_USER_REMAINING_WORKOUTS_REQUEST'
export const GET_USER_REMAINING_WORKOUTS_SUCCESS = 'GET_USER_REMAINING_WORKOUTS_SUCCESS'
export const GET_USER_REMAINING_WORKOUTS_FAILURE = 'GET_USER_REMAINING_WORKOUTS_FAILURE'

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE'

export const RESET_USER_STATE = 'RESET_USER_STATE'

export const UPDATE_USER_STATUS_REQUEST = 'UPDATE_USER_STATUS_REQUEST'
export const UPDATE_USER_STATUS_SUCCESS = 'UPDATE_USER_STATUS_SUCCESS'
export const UPDATE_USER_STATUS_FAILURE = 'UPDATE_USER_STATUS_FAILURE'

// Workouts List
export const GET_WORKOUTS_REQUEST = 'GET_WORKOUTS_REQUEST'
export const GET_WORKOUTS_SUCCESS = 'GET_WORKOUTS_SUCCESS'
export const GET_WORKOUTS_FAILURE = 'GET_WORKOUTS_FAILURE'

// Workouts Details
export const GET_WORKOUT_BY_ID_REQUEST = 'GET_WORKOUT_BY_ID_REQUEST'
export const GET_WORKOUT_BY_ID_SUCCESS = 'GET_WORKOUT_BY_ID_SUCCESS'
export const GET_WORKOUT_BY_ID_FAILURE = 'GET_WORKOUT_BY_ID_FAILURE'

export const CREATE_WORKOUT_REQUEST = 'CREATE_WORKOUT_REQUEST'
export const CREATE_WORKOUT_SUCCESS = 'CREATE_WORKOUT_SUCCESS'
export const CREATE_WORKOUT_FAILURE = 'CREATE_WORKOUT_FAILURE'

export const UPDATE_WORKOUT_REQUEST = 'UPDATE_WORKOUT_REQUEST'
export const UPDATE_WORKOUT_SUCCESS = 'UPDATE_WORKOUT_SUCCESS'
export const UPDATE_WORKOUT_FAILURE = 'UPDATE_WORKOUT_FAILURE'

export const RESET_WORKOUT_STATE = 'RESET_WORKOUT_STATE'

// Scheduled Workouts List
export const GET_SCHEDULED_WORKOUTS_REQUEST = 'GET_SCHEDULED_WORKOUTS_REQUEST'
export const GET_SCHEDULED_WORKOUTS_SUCCESS = 'GET_SCHEDULED_WORKOUTS_SUCCESS'
export const GET_SCHEDULED_WORKOUTS_FAILURE = 'GET_SCHEDULED_WORKOUTS_FAILURE'

export const GET_SCHEDULED_WORKOUT_FOR_WEEK_REQUEST = 'GET_SCHEDULED_WORKOUT_FOR_WEEK_REQUEST'
export const GET_SCHEDULED_WORKOUT_FOR_WEEK_SUCCESS = 'GET_SCHEDULED_WORKOUT_FOR_WEEK_SUCCESS'
export const GET_SCHEDULED_WORKOUT_FOR_WEEK_FAILURE = 'GET_SCHEDULED_WORKOUT_FOR_WEEK_FAILURE'

// Scheduled Workouts Details
export const GET_SCHEDULED_WORKOUT_BY_ID_REQUEST = 'GET_SCHEDULED_WORKOUT_BY_ID_REQUEST'
export const GET_SCHEDULED_WORKOUT_BY_ID_SUCCESS = 'GET_SCHEDULED_WORKOUT_BY_ID_SUCCESS'
export const GET_SCHEDULED_WORKOUT_BY_ID_FAILURE = 'GET_SCHEDULED_WORKOUT_BY_ID_FAILURE'

export const GET_SCHEDULED_WORKOUT_BY_DATE_REQUEST = 'GET_SCHEDULED_WORKOUT_BY_DATE_REQUEST'
export const GET_SCHEDULED_WORKOUT_BY_DATE_SUCCESS = 'GET_SCHEDULED_WORKOUT_BY_DATE_SUCCESS'
export const GET_SCHEDULED_WORKOUT_BY_DATE_FAILURE = 'GET_SCHEDULED_WORKOUT_BY_DATE_FAILURE'

export const CREATE_SCHEDULED_WORKOUT_REQUEST = 'CREATE_SCHEDULED_WORKOUT_REQUEST'
export const CREATE_SCHEDULED_WORKOUT_SUCCESS = 'CREATE_SCHEDULED_WORKOUT_SUCCESS'
export const CREATE_SCHEDULED_WORKOUT_FAILURE = 'CREATE_SCHEDULED_WORKOUT_FAILURE'

export const UPDATE_SCHEDULED_WORKOUT_STATUS_REQUEST = 'UPDATE_SCHEDULED_WORKOUT_STATUS_REQUEST'
export const UPDATE_SCHEDULED_WORKOUT_STATUS_SUCCESS = 'UPDATE_SCHEDULED_WORKOUT_STATUS_SUCCESS'
export const UPDATE_SCHEDULED_WORKOUT_STATUS_FAILURE = 'UPDATE_SCHEDULED_WORKOUT_STATUS_FAILURE'
